spring:
  application:
    name: role-permission-management
  
  datasource:
    url: jdbc:h2:mem:rbac_system;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:demo@example.com}
    password: ${MAIL_PASSWORD:demopassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

# Application Configuration
app:
  jwtSecret: mySecretKeyForRBACSystem123456789012345678901234567890
  jwtExpirationMs: 86400000 # 24 hours
  superadmin:
    username: superadmin
    password: SuperAdmin@123
    email: superadmin@system.com

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.rbac: DEBUG
    org.hibernate.SQL: DEBUG